# Generated by Django 4.2.28 on 2026-02-21 01:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name must contain only lower case alphanumeric characters, and underscores', regex='^[a-z0-9_]+$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
