# Generated by Django 5.2.11 on 2026-02-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='study_definition',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
