# Generated by Django 4.2.28 on 2026-02-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocol_api', '0002_protocol_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
